// <auto-generated />
namespace FacebookLivePoll.Web.Migrations.IdentityMConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ini));
        
        string IMigrationMetadata.Id
        {
            get { return "201705122255046_ini"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
