// <auto-generated />
namespace FacebookLivePoll.Web.Migrations.DbMConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbi));
        
        string IMigrationMetadata.Id
        {
            get { return "201705122254450_dbi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
